### PR TITLE
Fix "Invalid containerPort" error with EXPOSE Dockerfile instruction

### LINKED ISSUE #25: Failure to parse / stringify EXPOSE command: Invalid containerPort
Reported downstream as balena-io/balena-cli/issues/1511 :
[balena build fails with "Invalid containerPort: [80]"](https://github.com/balena-io/balena-cli/issues/1511)

### PR DESCRIPTION
**Pull request by pdcastro**
Note there are 2 commits, and the larger one is only prettifying the test Dockerfiles (easier to review them separately...)

Resolves: #25 
Connects-to: balena-io/balena-cli/issues/1511
Change-type: patch
Signed-off-by: Paulo Castro <paulo@balena.io>

### CODE REVIEW

File: tests/tests.ts [hunk 1]
```diff
@@ -88,6 +92,10 @@ describe('Transpose a Dockerfile', () => {
 			stripIndents`
 			FROM ubuntu
 			COPY ["${opts.hostQemuPath}","${opts.containerQemuPath}"]
+			ARG foo=bar zip
+			ARG myVar
+			EXPOSE 80 123/udp
+			EXPOSE 8080
```
Comment (pdcastro) [inline tests/tests.ts:98]: Before the fix, the problem was that, for example, an input line of `EXPOSE 8080` would produce an incorrect output of `EXPOSE [8080]`.

File: src/index.ts [hunk 2]
```diff
@@ -104,23 +104,22 @@ const commandToTranspose = (command: Command): CommandTransposer => {
...
-
 	if (_.isArray(args)) {
 		let ret = '';
 		// Handle command meta-arguments (like --from=stage)
 		if (args[0] != null && args[0].startsWith('--')) {
 			ret += args[0] + ' ';
 			args = args.slice(1);
 		}
+		if (spaceSeparatedArrayCommands.includes(commandName)) {
+			return ret + args.join(' ');
```
Comment (pdcastro) [inline src/index.ts:121]: This is the key fix. Commands like ARG and EXPOSE should generate (stringify as) space-separated lists, without square brackets.

**Comment by mdtusz** [comment]
Thanks for the super quick turnaround on this!

**Review by dfunckt — APPROVED** [review]
